routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AltaBajaController, AnuncioController, AsesoriaController, CarreraController, MaestroController};
use App\Http\Controllers\{DepartamentoController, GrupoController, HorarioController,Maestro,Controller};
use App\Http\Controllers\{MateriaAsignadaController, MateriaController, TipoUsuarioController, UsuarioController, VacanteController};

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/horario', [App\Http\Controllers\HomeController::class, 'horario'])->name('horario');

Route::resource('altas_bajas', AltaBajaController::class)->middleware('auth');
Route::resource('anuncio', AnuncioController::class)->middleware('auth');
Route::resource('asesoria', AsesoriaController::class)->middleware('auth');
Route::resource('carrera', CarreraController::class)->middleware('auth');
Route::resource('departamento', DepartamentoController::class)->middleware('auth');
Route::resource('grupo', GrupoController::class)->middleware('auth');
Route::resource('horario', HorarioController::class)->middleware('auth');
Route::resource('materias_asignadas', MateriaAsignadaController::class)->middleware('auth');
Route::resource('maestro', MaestroController::class)->middleware('auth');
Route::resource('materia', MateriaController::class)->middleware('auth');
Route::resource('tipo_usuario', TipoUsuarioController::class)->middleware('auth');
Route::resource('usuario', UsuarioController::class)->middleware('auth');
Route::resource('vacante', VacanteController::class)->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id_carrera',
        'id_grupo',
        'id_tipo_usuario',
        'matricula',
        'nombre',
        'apellido_paterno',
        'apellido_materno',
        'sexo',
        'num_telefono',
        'num_telefono2',
        'ubicacion',
        'descripcion',
        'foto',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getGetImageAttribute(){
        if($this->foto){
            return url("storage/$this->foto");
        }
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap_custom.css') }}" rel="stylesheet">
    <link href="{{ asset('css/estilos.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark shadow-sm" style="background-color: #151830; width:100%;">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="{{ asset('img/upq.svg') }}" height="32" width="32"> {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar sesión') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Crear usuario') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Alumno
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('materias_asignadas.index') }}">
                                        Materias asignadas
                                    </a>
                                    <a class="dropdown-item" href="{{ route('horario.index') }}">
                                        Horario
                                    </a>
                                    <a class="dropdown-item" href="{{ route('asesoria.index') }}">
                                        Asesorías
                                    </a>
                                    <a class="dropdown-item" href="{{ route('anuncio.index') }}">
                                        Anuncios
                                    </a>
                                    <a class="dropdown-item" href="{{ route('vacante.index') }}">
                                        Vacantes
                                    </a>
                                    <a class="dropdown-item" href="{{ route('maestro.index') }}">
                                        Información de PA y PTC
                                    </a>
                                    <a class="dropdown-item" href="{{ route('altas_bajas.index') }}">
                                        Altas y bajas de materias
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Sistema
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('usuario.index') }}">
                                        Usuarios
                                    </a>
                                    <a class="dropdown-item" href="{{ route('tipo_usuario.index') }}">
                                        Tipos de usuarios
                                    </a>
                                    <a class="dropdown-item" href="{{ route('grupo.index') }}">
                                        Grupos
                                    </a>
                                    <a class="dropdown-item" href="{{ route('carrera.index') }}">
                                        Carreras
                                    </a>
                                    <a class="dropdown-item" href="{{ route('departamento.index') }}">
                                        Departamentos
                                    </a>
                                    <a class="dropdown-item" href="{{ route('materia.index') }}">
                                        Materias
                                    </a>
                                </div>
                            </li>
                            @inject('UsuarioModel', 'App\Models\User')
                            @php
                                $usuario = $UsuarioModel::find(Auth::user()->id);
                            @endphp
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle m-auto" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    @if($usuario->get_image)
                                        <img src="{{ $usuario->get_image }}" class="rounded-circle" width="25" height="25"> &nbsp;
                                    @else
                                        @if($usuario->sexo == 2)
                                            <img src="{{ asset('img/poli.png') }}" class="rounded-circle" width="25" height="25"> &nbsp;
                                        @else
                                            <img src="{{ asset('img/polo.png') }}" class="rounded-circle" width="25" height="25"> &nbsp;
                                        @endif
                                    @endif
                                    {{ Auth::user()->nombre }} {{ Auth::user()->apellido_paterno }} {{ Auth::user()->apellido_materno }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>